  services:
  - type: web
    name: upload-service
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AWS_REGION
        value: us-east-1
      - key: PORT
        value: 8003
      


      